List available features
buildingSMART/ifc-gherkin-rules pull request #101
Opened 2023-10-18 19:02 UTC by JTurbakiewicz

2023-10-18 19:09 UTC, JTurbakiewicz commented
Very simple script listing the rules present in the repository. Output is a CSV file, which can be parsed to Excel quite nicely:

![image](https://github.com/buildingSMART/ifc-gherkin-rules/assets/43152548/d907a4e8-acf1-42ca-859e-0e7ef47e84a6)

I can make an .exe file out of the script of course.

2023-11-01 09:03 UTC, Ghesselink requested changes
Looks good. 

Should we also add a recent version of the .csv output in the repository?

2023-11-01 10:47 UTC, Ghesselink approved these changes

2023-11-01 10:50 UTC, Ghesselink commented
@evandroAlfieri That makes sense. It happens quite often already that a PR evolves to a bigger discussion and then remains open indeed .. Let's merge it then 

@JTurbakiewicz I've approved the changes. If I'm right you can merge the PR when you resolve the conversations (1 approving review).

2023-11-02 17:54 UTC, JTurbakiewicz commented on features/resources/list_repository/_list_rules.py
> +            tags = ["@disabled", "@implementer-agreement", "@informal-proposition"]
I agree with the comment. At the moment I will resolve it based on Evandros good point, but in the future something to think about.

2023-11-02 17:55 UTC, JTurbakiewicz commented on features/resources/list_repository/_list_rules.py
> +            information_about_feature["rule_tag"] = rule_tag[0].upper()[1:]
I added a simple check len(item) == 4, eg. @als

Obviously that's just a super simple check, but keeping with the spirit of merging quick, should work just fine.

2023-11-02 18:00 UTC, merged