Convention improvements
buildingSMART/ifc-gherkin-rules pull request #106
Opened 2023-11-01 10:04 UTC by Ghesselink

Rule-convention improvements without automated script of https://github.com/buildingSMART/ifc-gherkin-rules/pull/74

2023-11-01 21:03 UTC, evandroAlfieri requested changes
Looks very good, great work @Ghesselink 
I've suggested some minor modifications. See if you need help from @JTurbakiewicz for ALS006 and 007

2023-11-04 05:16 UTC, Ghesselink commented on features/ALS006_Alignment-horizontal-shape-representation.feature
@JTurbakiewicz 

Shall we describe the `ALS003` rule as 
`The rule verifies that IfcAlignmentCant is represented correctly with a 3D curve and attributes named IfcSegmentedReferenceCurve. ? `

And `ALS007` as :
`The rule verifies that IfcAlignmentHorizontal is represented correctly with a 2D curve and either an IfcCompositeCurve, IfcIndexedPolycurve or IfcPolyline.`

?

2023-11-04 05:20 UTC, Ghesselink commented on features/GEM004_Constraints-on-representation-identifiers.feature
Changed to 
`The rule verifies that shape representations adhere to the permissible values outlined in the CSV files found in the 'features/resources/{attribute}.csv' folder, as specified in the documentation.`
 
 Hope that is ok. 
 https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/7cb88aac47ae029df99a59c96f452a49580aa829

2023-11-04 05:20 UTC, Ghesselink commented on features/GEM005_Building-shape-representation.feature
>  @ALS
https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/ab1fd90f09972b40b72424f55f35d7d9b60ba074

2023-11-04 05:21 UTC, Ghesselink commented on features/ALS007_Alignment-vertical-shape-representation.feature
> +https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcAlignmentHorizontal.htm
https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/38318326f6fa9f782f6167203641de919196b8f2

2023-11-04 05:22 UTC, Ghesselink commented on features/SPS003_Correct-containment-of-assemblies.feature
> +The rule verifies that IfcElement that are aggregated in another IfcElement must not be contained using IfcRelContainedInSpatialStructure.
https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/1a69e85db6446af3a9752f0c2e5201afc17c93ba

2023-11-04 05:23 UTC, Ghesselink commented on features/GRP001_Acyclic-groups.feature
>  The rule verifies that all the IfcGroups are acyclic.
https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/3b327b18cb9f2258e308dfb0aa07a31242ae16d3

2023-11-04 05:24 UTC, Ghesselink commented on features/SPS006_Elements-referenced-in-Spatial-structures.feature
> +The rule verifies that if IfcElements are positioned wrt IfcPositioning elements, then they must be also referenced (instead of contained) into a IfcSpatialStructure element
https://github.com/buildingSMART/ifc-gherkin-rules/pull/106/commits/4c311e7aa2fb4451bc1234b9505dd932c82ddc13

2023-11-04 06:28 UTC, Ghesselink commented on features/GEM005_Building-shape-representation.feature
>  @ALS
https://github.com/buildingSMART/ifc-gherkin-rules/pull/74

Note to myself to add this to the automated checks.

2023-11-04 12:33 UTC, JTurbakiewicz commented on features/ALS006_Alignment-horizontal-shape-representation.feature
Hi,

Makes sense to unify the descriptions. I'm fine with your proposal, just ALS007 is IfcAlighnmentVertical instead of Horizontal + we also need to unify ALS006. 

Alternatively we can go try going with slightly more formal (not sure if that's good :) ) :

ALS003

`The rule verifies that IfcAlignmentCant is represented correctly with representation type Curve3D and representation item IfcSegmentedReferenceCurve.`

ALS006

`The rule verifies that IfcAlignmentHorizontal is represented correctly with representation type Curve2D and representation item either IfcCompositeCurve or IfcIndexedPolycurve or IfcPolyline.`

ALS007

`The rule verifies that IfcAlignmentVertical is represented correctly with representation type Curve3D and representation item IfcGradientCurve.`

2023-11-04 17:11 UTC, Ghesselink commented on features/ALS006_Alignment-horizontal-shape-representation.feature
> ust ALS007 is IfcAlighnmentVertical instead of Horizontal
Oops, missed that ..

Sounds fine :) It seems its unified now. 

https://github.com/buildingSMART/ifc-gherkin-rules/commit/ebd26b07079acf5aa8a18385ac7ddfad0cd7cc65

2023-11-16 09:32 UTC, evandroAlfieri approved these changes
well done guys. Let's merge

2023-11-16 13:40 UTC, merged