IFC102 - Deprecation IFC4X3
buildingSMART/ifc-gherkin-rules pull request #207
Opened 2024-06-10 10:06 UTC by Ghesselink

Validating absence of deprecated entities, attributes and enumerated values as described in 
https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/content/introduction.htm#Deprecation

2024-06-12 14:03 UTC, evandroAlfieri requested changes

2024-06-12 14:03 UTC, evandroAlfieri commented on features/IFC102_Deprecation-IFC4X3.feature
> +Feature: IFC102 - Deprecation IFC4X3
```suggestion
Feature: IFC102 - Absence of entities deprecated by IFC 4.3
```
Please change file name accordingly

2024-06-13 12:30 UTC, evandroAlfieri approved these changes

2024-06-14 02:22 UTC, civilx64 requested changes

2024-06-14 15:39 UTC, Ghesselink commented on test/files/ifc102/pass-ifc102-scenario03-IfcCableCarrierFitting_enum_type_value_CROSS.ifc
Found the error. 
When comparing a `attribute` with a set of `values` the equality check is actually difference if multiple values are accepted, e.g. `{'TEE', 'CROSS', 'REDUCER'}`

In case of is equal, **one** of the values must be equal to the observed value: 
`pred(observed_v, value)`

However, with non-equality, **all** of the values must be not equal to the observed value.
`all(pred(observed_v, v) for v in value)`

Changed this 
https://github.com/buildingSMART/ifc-gherkin-rules/commit/be405b215f8502d87062a4cbf32b930b33005172

2024-06-14 15:43 UTC, Ghesselink commented on features/IFC102_Absence-of-deprecated-entities.feature
> +      | IfcCivilElementType |
Added https://github.com/buildingSMART/ifc-gherkin-rules/commit/ed46dbcf656ec37418b5301b3755c975fb584100

2024-06-14 15:45 UTC, Ghesselink commented on features/IFC102_Absence-of-deprecated-entities.feature
> +       | IfcGeographicElement | "SOIL_BORING_POINT" |
added

2024-06-14 21:37 UTC, civilx64 approved these changes

2024-06-14 21:39 UTC, civilx64 approved these changes

2024-06-15 00:09 UTC, merged