fix-ivs12-hotfix-pse001-trailing-whitespaces
buildingSMART/ifc-gherkin-rules pull request #216
Opened 2024-06-13 17:35 UTC by Ghesselink

Strings with whitespaces seem equal, but are not.
![image](https://github.com/buildingSMART/ifc-gherkin-rules/assets/54070862/8e856224-214c-4fc1-ac28-c40e83d75f08)

![image](https://github.com/buildingSMART/ifc-gherkin-rules/assets/54070862/27fbd6f6-6fa5-4608-93af-55ad2887f2de)

In [pset_definitions.csv](https://github.com/buildingSMART/ifc-gherkin-rules/compare/fix-ivs12-hotfix-pse001-trailing-whitespaces?expand=1#diff-fdb59cf819921c6fb7299410dfdefbe48e1b7da3a2abed3f7b062c6cdda59235), the only thing that changed is the whitespace after `'IfcThermalTransmitanceMeasure '`

2024-06-13 17:45 UTC, evandroAlfieri approved these changes
lgtm

2024-06-14 04:34 UTC, civilx64 requested changes

2024-06-14 04:34 UTC, civilx64 commented on features/resources/IFC2X3/pset_definitions.csv
> +Pset_AirSideSystemInformation,"['IfcSpatialStructureElement', 'IfcSystem']",,"[{'property_name': 'Name', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcLabel', 'unit_type':
```suggestion
Pset_AirSideSystemInformation,"['IfcSpatialStructureElement', 'IfcSystem']",,"[{'property_name': 'Name', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcLabel', 'unit_type': 'None'}}, {'property_name': 'Description', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcLabel', 'unit_type': 'None'}}, {'property_name': 'AirSideSystemType', 'property_type': 'IfcPropertyEnumeratedValue', 'data_type': {'instance': 'PEnum_AirSideSystemType', 'values': ['CONSTANTVOLUME', 'CONSTANTVOLUMESINGLEZONE', 'CONSTANTVOLUMEMULTIPLEZONEREHEAT', 'CONSTANTVOLUMEBYPASS', 'VARIABLEAIRVOLUME', 'VARIABLEAIRVOLUMEREHEAT', 'VARIABLEAIRVOLUMEINDUCTION', 'VARIABLEAIRVOLUMEFANPOWERED', 'VARIABLEAIRVOLUMEDUALCONDUIT', 'VARIABLEAIRVOLUMEVARIABLEDIFFUSERS', 'VARIABLEAIRVOLUMEVARIABLETEMPERATURE', 'OTHER', 'NOTKNOWN', 'UNSET\n']}}, {'property_name': 'AirSideSystemDistributionType', 'property_type': 'IfcPropertyEnumeratedValue', 'data_type': {'instance': 'PEnum_AirSideSystemDistributionType', 'values': ['SINGLEDUCT', 'DUALDUCT', 'MULTIZONE', 'OTHER', 'NOTKNOWN', 'UNSET']}}, {'property_name': 'TotalAirflow', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcVolumetricFlowRateMeasure', 'unit_type': ['VOLUMETRICFLOWRATEUNIT']}}, {'property_name': 'EnergyGainTotal', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPowerMeasure', 'unit_type': ['POWERUNIT']}}, {'property_name': 'AirflowSensible', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcVolumetricFlowRateMeasure', 'unit_type': ['VOLUMETRICFLOWRATEUNIT']}}, {'property_name': 'EnergyGainSensible', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPowerMeasure', 'unit_type': ['POWERUNIT']}}, {'property_name': 'EnergyLoss', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPowerMeasure', 'unit_type': ['POWERUNIT']}}, {'property_name': 'LightingDiversity', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPositiveRatioMeasure', 'unit_type': 'None'}}, {'property_name': 'InfiltrationDiversitySummer', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPositiveRatioMeasure', 'unit_type': 'None'}}, {'property_name': 'InfiltrationDiversityWinter', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPositiveRatioMeasure', 'unit_type': 'None'}}, {'property_name': 'ApplianceDiversity', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPositiveRatioMeasure', 'unit_type': 'None'}}, {'property_name': 'LoadSafetyFactor', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPositiveRatioMeasure', 'unit_type': 'None'}}, {'property_name': 'HeatingTemperatureDelta', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcThermodynamicTemperatureMeasure', 'unit_type': ['THERMODYNAMICTEMPERATUREUNIT']}}, {'property_name': 'CoolingTemperatureDelta', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcThermodynamicTemperatureMeasure', 'unit_type': ['THERMODYNAMICTEMPERATUREUNIT']}}, {'property_name': 'Ventilation', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcVolumetricFlowRateMeasure', 'unit_type': ['VOLUMETRICFLOWRATEUNIT']}}, {'property_name': 'FanPower', 'property_type': 'IfcPropertySingleValue', 'data_type': {'instance': 'IfcPowerMeasure', 'unit_type': ['POWERUNIT']}}]"
```

There are 3-4 unquoted values for the "instance" keys under "data_type" for properties such as ApplianceDiversity and LightingDiversity that are causing JSON Decode errors on the model data provided with the bug report.  The suggested change should fix this.

2024-06-14 12:10 UTC, civilx64 approved these changes

2024-06-14 12:11 UTC, merged