IVS-176/VRT000 - Virtual Elements
buildingSMART/ifc-gherkin-rules pull request #313
Opened 2024-10-23 15:00 UTC by Ghesselink

2024-10-27 10:27 UTC, aothms requested changes
I guess..

Regarding "Virtual elements are not displayed, do not have quantities", they can be displayed, the IFC spec says **usually** not displayed. The not have quantities bit I'd say is misleading.

2024-10-29 12:40 UTC, evandroAlfieri requested changes

2024-10-29 12:40 UTC, evandroAlfieri commented on features/VRT000_Virtual-elements.feature
> +    The rule verifies the presence of spatial elements used to provide imaginary, placeholder, or provisional areas (e.g. clearance), volumes, and boundaries.
```suggestion
    The rule verifies the presence of IFC entities used to model special elements providing imaginary, placeholder, or provisional areas (e.g. clearance), volumes, and boundaries. 
```

2024-10-29 12:40 UTC, evandroAlfieri commented on features/VRT000_Virtual-elements.feature
> +    Virtual elements are not displayed, do not have quantities, materials, or other measures.
```suggestion
```

2024-11-01 11:25 UTC, merged