Incorporate ALS fixes (IVS-186)
buildingSMART/ifc-gherkin-rules pull request #320
Opened 2024-11-04 05:28 UTC by civilx64

1. Upgrade to newer version of ifcopenshell to avoid bug in ALS016 related to clothoid spirals in imperial units.

2. Adjust for the total length of vertical segments so that ALS017 checks are performed correctly.

(IVS-186, IVS-53)

2024-11-04 10:25 UTC, Ghesselink requested changes
- Can you check whether you checked out the right commit from development? The [updates made in the ALB012 branc](https://github.com/buildingSMART/ifc-gherkin-rules/pull/300/commits/afdc400d3aaf2c45e9378a06d7372e8839c9a91e)h are modified along with these commits. 
- I'm getting passed results for ALS017. Could this be that this has to do with the ifcopenshell version? I see the latest release of IfcOpenShell is 0.8.0, where do I find 0.8.1?

Edit; I've manually updated my conda environment to python3.12 and [ifcopenshell commit 92b63a0](https://github.com/IfcOpenBot/IfcOpenShell/commit/92b63a0), but still with the same result :(
![image](https://github.com/user-attachments/assets/5e40f625-51d5-486f-aee5-33895dad1e82)

2024-11-05 11:11 UTC, Ghesselink commented
There are still some schema errors regarding the conversion. I'll also have a look 
![image](https://github.com/user-attachments/assets/80aa623e-4a72-4110-b54d-143783a89540)
(e.g. for pass-als017-scenario01-imperial_continuous.ifc)

2024-11-05 19:33 UTC, civilx64 commented on features/environment.py
> +    context.scenario_outcome_state.append(
The commit you noted, afdc400d3aaf2c45e9378a06d7372e8839c9a91e, was applied but my merge of ALB012 stomped over it.  I have cherry-picked it back to the top of the log:

![image](https://github.com/user-attachments/assets/cf11a12c-818b-4c82-9326-58ed83b90d01)

2024-11-05 19:38 UTC, civilx64 commented
> I'm getting passed results for ALS017. Could this be that this has to do with the ifcopenshell version? I see the latest release of IfcOpenShell is 0.8.0, where do I find 0.8.1?

> Edit; I've manually updated my conda environment to python3.12 and [ifcopenshell commit 92b63a0](https://github.com/IfcOpenBot/IfcOpenShell/commit/92b63a0), but still with the same result :(

Per slack discussion, you need to update the `.venv` on your local copy of the platform which you can do with the makefiles in [validate/34be62b94106d96d00b723e3b1e2fef32effb6af](https://github.com/buildingSMART/validate/tree/34be62b94106d96d00b723e3b1e2fef32effb6af)

2024-11-06 20:43 UTC, Ghesselink commented
> Per slack discussion, you need to update the .venv on your local copy of the platform which you can do with the makefiles in [validate/34be62b94106d96d00b723e3b1e2fef32effb6af](https://github.com/buildingSMART/validate/tree/34be62b94106d96d00b723e3b1e2fef32effb6af)

Yes, indeed. I thought I was not using venv anymore as I switched to have my own conda environment for running the server, but didn't realize venv was still running for the worker

2024-11-07 13:26 UTC, merged