IVS-178 - VER000
buildingSMART/ifc-gherkin-rules pull request #321
Opened 2024-11-04 15:57 UTC by Ghesselink

Simplified version of https://github.com/buildingSMART/ifc-gherkin-rules/pull/314

We concluded that the [concept template](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Object_Attributes/Revision_Control/content.html) does not provide enough context to set constraints on the sequence of given statements. The most simple version to colour blocks green should suffice.

2024-11-04 17:46 UTC, evandroAlfieri requested changes

2024-11-04 17:46 UTC, evandroAlfieri commented on features/VER000_Versioning-and-revision-control.feature
> +    The rule verifies the capability to track changes to building data over time and maintain a comprehensive history of those changes.
```suggestion
    The rule verifies the presence of IFC entities used to to track changes to building data over time and maintain a comprehensive history of those changes.
```

2024-11-05 21:44 UTC, civilx64 reviewed
The conversion-based unit for .DEGREE. was triggering a schema error so I removed it from the test files in ad84815b8fc00b7e89537bd9b98459431a8c2e68.  Small typo fix required in the `.feature` file and then we are good for UAT.

2024-11-05 21:44 UTC, civilx64 commented on features/VER000_Versioning-and-revision-control.feature
> +    The rule verifies the presence of IFC entities used to to track changes to building data over time and maintain a comprehensive history of those changes.
```suggestion
    The rule verifies the presence of IFC entities used to track changes to building data over time and maintain a comprehensive history of those changes.
```

2024-11-05 21:44 UTC, civilx64 commented on test/files/ver000/pass-ver000-owner_wrong_change_action.ifc
The name of this file indicates it relates to a specific case from the previous PR and is no longer needed.  I recommend deleting it unless there is a specific need to keep it.

2024-11-06 17:19 UTC, civilx64 approved these changes

2024-11-06 17:19 UTC, merged

2024-11-06 19:37 UTC, Ghesselink commented on features/VER000_Versioning-and-revision-control.feature
> +    The rule verifies the presence of IFC entities used to track changes to building data over time and maintain a comprehensive history of those changes.
We can still modify it. What about 
 >  The rule verifies the presence of IFC entities used to track changes to building data over time, providing information on the latest modifications, including when and by whom they were made.

2024-11-06 20:05 UTC, Ghesselink commented on features/VER000_Versioning-and-revision-control.feature
> +    The rule verifies the presence of IFC entities used to track changes to building data over time and maintain a comprehensive history of those changes.
>  but I'm not sure whether it's a well-understood word.

Well, I had to look it up myself :) @civilx64 ,as our only native English speaker of the team, what do you think? 

I would opt for the second sentence; it's clear, and consistency between the docs and validation service is also nice.