ALB004 - Alignment container
buildingSMART/ifc-gherkin-rules pull request #67
Opened 2023-05-14 21:50 UTC by JTurbakiewicz

2023-05-16 11:00 UTC, pjanck requested changes

2023-05-17 22:36 UTC, JTurbakiewicz commented on features/ALB004_Alignment-in-spatial-structure.feature
> +The rule verifies, that each IfcAlignment is contained in an IfcProject, but not contained in spatial structure.
Agreed. I am not yet 100% sure what the intended behavior established on the implementors forum is. 
@evandroAlfieri, could you please give a helping hand on this one?

2023-05-17 22:40 UTC, JTurbakiewicz commented on features/resources/spatial_CompositionTable.csv
> +IfcSpace,IfcSite
It comes from: https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Object_Composition/Aggregation/Spatial_Composition/content.html#General-Usage

2023-05-17 22:41 UTC, JTurbakiewicz commented on features/steps/thens/relations.py
> +                    break # TODO - > is the hierarchy important?
Agreed. More discussion here: https://github.com/buildingSMART/ifc-gherkin-rules/pull/65#discussion_r1193218299

2023-05-17 23:01 UTC, JTurbakiewicz commented on features/ALB004_Alignment-in-spatial-structure.feature
> +      And Each IfcAlignment must not be directly or indirectly contained in IfcSpatialElement
Ad.1. You're right. I thought it got mapped to IfcSpace, which connects to IfcProject in the .csv file. But it wasn't so, just the loop ended on IfcSpace, as it was the last element in the .csv. I'll fix that.

2023-05-17 23:04 UTC, JTurbakiewicz commented on features/ALB004_Alignment-in-spatial-structure.feature
> +      And Each IfcAlignment must not be directly or indirectly contained in IfcSpatialElement
Ad 2. The intention was:

Directly: IfcAlignment contained in IfcSpatialElement
Indirectly: IfcAlginment contained in anything but the IfcSpatialElement, which then is contained in IfcSpatialElement. However many levels there would be.

2023-06-27 15:04 UTC, evandroAlfieri commented on features/ALB004_Alignment-in-spatial-structure.feature
> +The rule verifies, that each IfcAlignment is contained in an IfcProject, but not contained in spatial structure.
Hi all, the promised update from the IF:
1. All instances of _IfcAlignment_ must be related to _IfcProject_ using the _IfcRelAggregates_ relationship - either directly or indirectly. The indirect case is when a child alignment is aggregated to a parent alignment. In this case, only the parent alignment shall be related to the project.
2. Instances of _IfcAlignment_ must not be related to spatial entities using the _IfcRelContainedInSpatialStructure_ relationship.

Can you try to adapt the rule accordingly?

2023-07-04 22:48 UTC, JTurbakiewicz commented on features/ALB004_Alignment-in-spatial-structure.feature
> +      And Each IfcAlignment must not be directly or indirectly contained in IfcSpatialElement
Changed the logic completely.

2023-07-24 16:02 UTC, pjanck commented on features/ALB004_Alignment-in-spatial-structure.feature
Considering

> The indirect case is when a child alignment is aggregated to a parent alignment.

and 

> Then Each IfcAlignment must be aggregated to IfcProject directly or indirectly

together with the code provided in the `features/steps/thens/relations.py`, I wonder what a hypothetical situation like the one below would produce:

> IfcProject --> IfcRelAggregates --> IfcSite --> IfcRelAggregates --> IfcAlignment 
> (project is aggregating a site which in turn aggregates an alignment)

Is this passing or failing? (It should fail in my opinion.)

2023-09-21 11:55 UTC, merged