handle markdown for testfiles
buildingSMART/ifc-gherkin-rules pull request #83
Opened 2023-09-21 19:17 UTC by Ghesselink

Hopefully a useful tool to generate markdown files for testfiles. 

    Usage:
    ------
    To generate markdown files:
        python3 test_main.py --generate-markdown

    To combine markdown generation with testing for a specific rule code:
        python3 test_main.py --generate-markdown grf001

    Explanation:
    ------------
    The '--generate-markdown' flag tells the script to create markdown files based on the tests.

    The 'grf001' in the second example represents a specific rule code. You can replace it with any valid rule code to test.

    The markdown generation process will take into account the specified rule code, if provided.

2023-09-22 09:36 UTC, aothms requested changes

2023-09-22 09:36 UTC, aothms commented on test/test_main.py
> +        handle_testfile_markdown(results, base)
I think I'd rather move this to a separate file altogether. The way it is currently written requires you to run the tests to generate markdown which I think is unnecessary.

2023-09-26 08:53 UTC, aothms commented
For SYS001 it generated some weird formatting (due to multiline errors?)

![afbeelding](https://github.com/buildingSMART/ifc-gherkin-rules/assets/1096535/37e38393-e4cf-4b62-b91e-b182e7b8a0c8)

https://github.com/buildingSMART/ifc-gherkin-rules/commit/1311f58bc5fe3e7fbc1ae7411e1cf11dc738cc9b

2023-09-27 21:13 UTC, Ghesselink commented
Answering @aothms 


> And for the pass results it generated a "Rule passed" message.

I followed the conventions in  https://github.com/buildingSMART/ifc-gherkin-rules/tree/main/features#readme . 
It makes somse sense to include the 'pass' files in, as that way it's still possible to add a description (for instance with 'ALB002'). 

> I tested your script on the GRP001 PR [...]  I didn't get any content in the error column for the fail files. Is that intended?

> For SYS001 it generated some weird formatting (due to multiline errors?)

I think for both GRP001 and SYS001 the error was due to multiline errors. The handling of multiple lines in one markdown cell seems to be problematic in github 
https://github.com/markdown-it/markdown-it/issues/406
https://stackoverflow.com/questions/47324785/how-can-i-add-a-table-with-multi-row-cells-to-a-readme-in-vsts/47335483#47335483

There are some workarounds, but the most straightforward and often used I think is just using html. This should be rendered well in Github. In case of multiple results pertaining to one rule, the table will have additional rows to accommodate each result. Furthermore, descriptions are adjustable even after generating a markdown file. 
The old markdown table will still be parsed in the script (for instance, when updating a description after 'Error')

After modifying the script (see also on the top of the PR). 
`SYS001`

![complete](https://github.com/buildingSMART/ifc-gherkin-rules/assets/54070862/2b98a4c2-4934-4c93-99f8-3727e5c3a6bb)

`GRP001`

![grp001](https://github.com/buildingSMART/ifc-gherkin-rules/assets/54070862/ebd1faec-83cf-4542-baed-a45a6557ba50)

2024-04-23 19:29 UTC, closed without merging